services:
  app:
    image: aoirint/lastfm_api_middleware:0.3.1
    restart: always
    environment:
      LASTFM_USER: ${LASTFM_USER:?}
      LASTFM_API_KEY: ${LASTFM_API_KEY:?}
      DUMP_PATH: ${DUMP_PATH:?}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:?}
    volumes:
      - "${HOST_DATA_DIR}:/data"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
